version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: assessment-postgres
    environment:
      POSTGRES_DB: assessment
      POSTGRES_USER: assessment
      POSTGRES_PASSWORD: assessment
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U assessment"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: assessment-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: assessment-app
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: assessment
      DB_USER: assessment
      DB_PASSWORD: assessment
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres-data:
