apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-practice
  labels:
    app: assessment-practice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assessment-practice
  template:
    metadata:
      labels:
        app: assessment-practice
    spec:
      containers:
      - name: assessment-practice
        image: assessment-practice:1.0.0
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: assessment-practice-service
  labels:
    app: assessment-practice
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: assessment-practice
